apiVersion: v1
kind: Service
metadata:
  name: my-first-service
  annotations:
    argocd.argoproj.io/ignore-resource-update: "true"
spec:
  selector:
    env: production
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels:
    env: prod
spec:
  containers:
    - name: myfirstcontainer
      image: nginx
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: example-container
        image: alpine
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 10"]
      restartPolicy: Never
