apiVersion: v1
kind: Service
metadata:
  name: my-first-service
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/ignore-resource-updates: "true"
spec:
  selector:
    env: prod
  ports:
    - name: https
      port: 80
      targetPort: 8084
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-wave: '0'
  name: myfirstpod
  labels:
    env: prod
spec:
  containers:
    - name: myfirstcontainer
      image: nginx
      env:
        - name: abc
          value: 123
---
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  template:
    spec:
      containers:
      - name: example-container
        image: alpine
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 10"]
      restartPolicy: Never
