apiVersion: v1
kind: Service
metadata:
  name: my-first-service
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/ignore-resource-updates: "true"
spec:
  selector:
    env: prod
  ports:
    - name: https
      port: 80
      targetPort: 8081
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.25.4
        env:
          - name: abc
            value: "1234"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-example-job
  annotations:
    argocd.argoproj.io/sync-wave: '1'
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      serviceAccountName: sa-argocd
      initContainers:
      - name: wait-for-deployment
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for my-app-deployment to fully roll out..."
          kubectl rollout status deployment/my-app-deployment --timeout=300s
      containers:
      - name: example-container
        image: alpine
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 10"]
      restartPolicy: Never
